DROP TABLE IF EXISTS TB_HEROIS;
CREATE TABLE TB_HEROIS (
  ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  NOME TEXT NOT NULL,
  PODER TEXT NOT NULL
)

---CREATE
INSERT INTO TB_HEROIS (NOME,PODER) VALUES ('Flash', 'velocidade'),('Aquaman','Falar com os animais'),('Batman', 'Rico')

--- read
SELECT * FROM TB_HEROIS;
SELECT * FROM TB_HEROIS WHERE NOME= 'Flahs';

--- update
update TB_HEROIS
SET NOME = 'GOKU',
SET PODER = 'KI'
WHERE ID= 1;